import psycopg2
con=psycopg2.connect(database="mydata",user="postgres",password="",host="localhost",port="5432")
c1=con.cursor()
c1.execute("select * from course")
data=c1.fetchall()
sid=int(input("enter student id"))
sname=int(input("enter student name"))
print("selecet course id from the following")
cid=int(input("enter course id"))
row=(sid,sname,cid)
c1.execute("insert into student values(%s,%s,%s)",row)
con.commit()
print("record inserted")
con.close()
